# Intent definition for template skill
#
#  (c) A. Dominik, 2020
#
skill = "SusiTime"
developer = "andreasdominik"


[inventory]
intents = ["SayTime"]
slots = []


# define slots:
# Types: Any/List/InstantTime/Currency/Number/Ordinal/...
#


# define phrases for intent recognition:
# exact, regex, part
#
[SayTime]
# disable_on_start = false
say_time_action_a = "exact: <<please|>> tell me what time it is <<please|>>"
say_time_action_b = "exact: what time is it <<please|>>"
say_time_action_c = "partial: do you happen to know what time it is"
