# Intent definition for template skill
#
#  (c) A. Dominik, 2020
#
skill = "SusiTime"
developer = "andreasdominik"


[inventory]
intents = ["SayTime"]
slots = []


# define slots:
# Types: Any/List/InstantTime/Currency/Number/Ordinal/...
#


# define phrases for intent recognition:
# exact, regex, part
#
[SayTime]
# disable_on_start = false
say_time_action_a = "exact: Quelle heure est-il"
say_time_action_b = "exact: Il est quelle heure"
