Snips.addText("de", :iam, "Ich bin dein Assistent")
Snips.addText("de", :isay, ["Ich soll sagen", "Ich sage", "Das Wort ist"])
Snips.addText("de", :bravo, "Bravo, du hast erfolgreich das Template installiert!")
Snips.addText("de", :noname, "Ich finde keinen Namen in der config Datei!")
Snips.addText("de", :dunno, "Ich habe nicht verstanden was ich sagen soll!")

Snips.addText("en", :iam, "I am your home assistant")
Snips.addText("en", :isay, ["You told me to say", "I say"])
Snips.addText("en", :bravo, "Bravo, you managed to install the template!")
Snips.addText("en", :bravo, "The template app is running!")
Snips.addText("en", :noname, "My name is not configured in the config file!")
Snips.addText("en", :dunno, "I did not catch what you want me to say!")
